theme = "sonokai"

[editor]
auto-save = true
bufferline = "always"
rulers = [120]
trim-trailing-whitespace = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal.space.n]
p = ":read /Users/hwasung_lee/.config/helix/templates/template.py"
s = ":read /Users/hwasung_lee/.config/helix/templates/template.sh"
